In [42]:
import numpy as np
from collections import Counter

In [43]:
with open('input8.txt', 'r') as f:
    x = f.readlines()
#print(x)
input_vals = [int(i) for i in x[0].split(',')]
#print(input_vals)

In [48]:
def count_vals(mat):
    ones = 0
    zeros = 0
    twos = 0
    for row in mat:
        d = Counter(row)
        for key in d.keys():
            if key == 1:
                ones += d[key]
            elif key == 0:
                zeros += d[key]
            elif key == 2:
                twos += d[key]
            else:
                print('Unknown symbols in image')
    return zeros, ones * twos
        

In [60]:
inp_pix = [int(x) for x in str(input_vals[0])]
i = 0
k = 0
img_layer = []
vals_z = []
vals_m = []
image = []
width = 25
height = 6
while i < len(inp_pix):
    img_layer.append(inp_pix[i:i+width])
    i += width
    k += 1
    if not k%6 and k > 0:
        image.append(img_layer)
        vals_z.append(count_vals(img_layer)[0])
        vals_m.append(count_vals(img_layer)[1])
        #print(count_vals(img_layer))
        img_layer = []

#print(image)

In [61]:
minpos = vals_z.index(min(vals_z))
print(vals_m[minpos])
    

1340


In [82]:
final_image = np.zeros((len(final_image),len(final_image[0])), dtype=int)
print(len(final_image))
flag = np.zeros((len(final_image),len(final_image[0])), dtype=int)
#flag[5,5] = 1
print(flag)


6
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [97]:

for layer in image:
    for k, row in enumerate(layer):
        for j, pixel in enumerate(row):
            if pixel != 2 and not flag[k, j]:
                final_image[k, j] = pixel
                flag[k,j] = 1
print(final_image)
from PIL import Image
img = Image.fromarray(final_image, 'RGB')
#img.save('my.png')
img.show()

[[1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0]]
